### ISSUE TITLE
Mouse pointer disappears when it moves to player area (with or without fullscreen)

### ISSUE THREAD

**Issue by josejuansanchez** [P2PSP/p2psp#15]
Low priority

**Comment by maniotrix** [comment]
I think this problem is due  to gtk version. Mouse pointer does not disappear using gtk 2.

Or may be libvlc needs to be updated.

**Comment by josejuansanchez** [comment]
@maniotrix You are right it looks like an issue with gtk3. I have been running the tests and seems to work fine for gtk2.

**Comment by maniotrix** [comment]
I have done a lot of research on this issue and no solution has been found yet.If the mouse pointer still disappears , It would be better to have only key input over drawing area/surface.

**Comment by josejuansanchez** [comment]
@maniotrix Could be possible to do a test using **Qt** instead of GTK?

I think could be a good idea to use Qt in order to check if the problem still occurs.

**Comment by maniotrix** [comment]
Yes It would be a good option to use Qt. But just because of this small problem , switching to Qt is not favourable.

If it is necessary we always have the option to use gtk2 in place of gtk3, because gtk2 solves this problem.

**Comment by maniotrix** [comment]
For now what I propose is that:

We should continue to use Gtk3.
As there is always a fullscreen toggle button in the main window, user can always switch to fullscreen mode with a mouse.
When user wants to go back to normal mode, the conventional "ESC" button can be pressed.
Now here first Player/Status Box will appear after pressing "ESC"(also duration until box disappears can be also specified). After that main window can be returned to its normal mode using fullscreen toggle button in PLayer/Status Box.

So what I want to say is that when app is in fullscreen mode, we can use "ESC" key to show/hide Player/Status Box. From Player/Status Box we can always  toggle fullscreen mode with mouse.

**Comment by josejuansanchez** [comment]
> @maniotrix:
> Yes It would be a good option to use Qt. But just because of this small problem , switching to Qt is not > favourable.

Why is not favourable to switch to Qt?

**Comment by maniotrix** [comment]
Due to time constraint.I do not have any experience with Qt.

**Comment by josejuansanchez** [comment]
Ok! No problem :)

**Comment by maniotrix** [comment]
@JJ Thanks for your support.

**Comment by JJ** [comment]
You probably mean @josejuansanchez :-)

**Comment by josejuansanchez** [comment]
@JJ @maniotrix :-)

**Comment by maniotrix** [comment]
@JJ Sorry :)

**Comment by JJ** [comment]
No problem, I love the other JJ's work :-)

**Comment by josejuansanchez** [comment]
@JJ Thanks! I love your work too :)

**Comment by cristobalmedinalopez** [comment]
It was fixed
