### ISSUE TITLE
Import/Export channels list

### ISSUE THREAD

**Issue by josejuansanchez** [P2PSP/p2psp#20]

**Comment by cristobalmedinalopez** [comment]
Maybe we should think what is the best file format and which information we want to store into the file. 
I think that we need to store: channel name, description, thumbnail, splitter address and splitter port. Anything else?

**Comment by josejuansanchez** [comment]
We can use a JSON file similar to this:
```
{
    {
      "name" : "channel 1",
      "description" : "...",
      "thumbnail"  : "http://url.test/thumbnail.jpg",
      "splitter_addr" : "150.214.150.68", 
      "splitter_port" :  4551
    },
    {
      "name" : "channel 2",
      "description" : "...",
      "thumbnail"  : "http://url.test/thumbnail.jpg",
      "splitter_addr" : "150.214.150.68", 
      "splitter_port" :  4551
    },
    ...
}
```

**Comment by cristobalmedinalopez** [comment]
Ok, it's a good option.

**Comment by maniotrix** [comment]
Yes for our purposes  JSON is good.

**Comment by jp-garcia-ortiz** [comment]
Yes, JSON is a good solution, useful also for the REST server.

2015-06-09 9:39 GMT-04:00 Prince <notifications@github.com>:

**Comment by cristobalmedinalopez** [comment]
Great job! Thanks.
