### ISSUE TITLE
Display information about download and upload speed.

### ISSUE THREAD

**Issue by cristobalmedinalopez** [P2PSP/p2psp#22]
Display information about download and upload speed in the player window in real time. Moreover, in order to keep a log, would it be possible to use a chart?

**Comment by maniotrix** [comment]
Yes using  charts is possible and  rendering the down/up speed log for some time period like day/week/months in gui.

**Comment by cristobalmedinalopez** [comment]
Close this issue. I'll create another for the chart (it's not a priority).
