### ISSUE TITLE
Error: glade requires gtk+ 3.12

### ISSUE THREAD

**Issue by cristobalmedinalopez** [P2PSP/p2psp#27]
On every machine that I try to run the GUI I get this error:
```
Traceback (most recent call last):
  File "p2psp_application_gui.py", line 12, in <module>
    App_Window = Main_Window()
  File "/home/cmedina/p2psp/src/view/main_window.py", line 14, in __init__
    self.interface = file_util.get_user_interface('glade', '../data/glade/mainwindow.glade')
  File "/home/cmedina/p2psp/src/common/file_util.py", line 16, in get_user_interface
    builder.add_from_file(fName)
gi._glib.GError: ../data/glade/mainwindow.glade: required gtk+ version 3.12, current version is 3.10
```
Why gtk+ 3.12 is required? Is there an easy way to resolve it?

The way to resolve it that I've found is not so easy for regular users (it's a little bit tedious)

**Comment by maniotrix** [comment]
The UI is build with glade 3. So minimum gtk+3 is required.

Therefore following changes  in this commit should resolve this issue: https://github.com/maniotrix/p2psp/commit/1777c0ef8738a830abe33ca0157a1fa5be54b6b2

Here 'requires' attribute in glade file is modified .

**Comment by cristobalmedinalopez** [comment]
Ok, thanks!
I think most people use gtk3 but not all 3.12.

**Comment by josejuansanchez** [comment]
Thanks @maniotrix!

Could you do a pull request to add this change to the repository?

**Comment by maniotrix** [comment]
Please find the resolution of this issue here: https://github.com/maniotrix/p2psp/commit/248ee57b10af257f8277d4a867365e48fa52ea52
