### ISSUE TITLE
Buffer progress bar should not be displayed (all time) in the full screen window

### ISSUE THREAD

**Issue by cristobalmedinalopez** [P2PSP/p2psp#32]
When the buffer is 100%, the progress bar should disappear whether the window is in full screen.

**Comment by maniotrix** [comment]
Besides that issue I think it should be shown only  when buffer_status is being changed after the peer starts(neither before 1% nor after 100%).
What do you guys suggest?

**Comment by josejuansanchez** [comment]
@maniotrix @cristobalmedinalopez I think that's a good idea.
