### ISSUE TITLE
Design of the Channel List in the GUI

### ISSUE THREAD

**Issue by cristobalmedinalopez** [P2PSP/p2psp#39]
A review is necessary.

**Comment by maniotrix** [comment]
![screenshot from 2015-06-26 13 31 08](https://cloud.githubusercontent.com/assets/7295721/8373183/f1ebc85e-1c07-11e5-9251-4ac5da79c78b.png)
![screenshot from 2015-06-26 13 31 54](https://cloud.githubusercontent.com/assets/7295721/8373190/0a17700e-1c08-11e5-975f-1686b4101690.png)

**Comment by maniotrix** [comment]
Apart from what is shown in above images, channel's detailed description and also channel quality may be displayed in two ways:

#### when the mouse cursor moves to some channel ,then the channel's detail can be displayed in a custom popover dialog box/message box.
#### creating a revealer would also be a good option.Here channel's detail can be revealed from the bottom of channel box.

Please suggest any other options.
