### ISSUE TITLE
unique identity of p2psp channels json file

### ISSUE THREAD

**Issue by maniotrix** [P2PSP/p2psp#54]

**Comment by maniotrix** [comment]
One option would be to start the filename with p2psp.
for example : p2psp_some _exported_filename.

**Comment by cristobalmedinalopez** [comment]
Another option would be to use p2psp as an extension. For example: some_exported_filename.p2psp

**Comment by maniotrix** [comment]
Ok then file will end in p2psp extension.

**Comment by maniotrix** [comment]
Resolved in PR #56
